spring:
  h2:
    console:
      enabled: true
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: welcome1

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect